design_methods/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, ListView, CreateView
from design_methods.views import *
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# URIs for user-specific views and pages
# These are included in the main url patterns with a "/users/" prefix
user_urlpatterns = patterns('design_methods.views',
    url(r'^$', UserList.as_view()),
    url(r'^(?P<pk>\d+)/$', UserDetails.as_view(), name='user_details'),
    url(r'^new/$', Register.as_view(), name="register"),
)

# URIs for messages
# TODO message lists, details, and replies
message_urlpatterns = patterns('design_methods.views',
    url(r'^$', 'list_messages'),
    url(r'^new/$', 'send_message'),
)

# URIs for methods
method_urlpatterns = patterns('design_methods.views',
    url(r'^$', 'list_methods'),
    url(r'^new/$', 'create_method'),
    url(r'^(?P<pk>\d+)/$', MethodDetails.as_view(), name='method_details'),
)

# Main URIs
urlpatterns = patterns('design_methods.views',
    url(r'^$', 'home', name='home'),
    url(r'^users/', include(user_urlpatterns)),
    url(r'^login/', login, {'template_name': 'sessions/login.html'}),
    url(r'^logout/', logout, {'next_page': '/'}),
    url(r'^messages/', include(message_urlpatterns)),
    url(r'^methods/', include(method_urlpatterns)),
)

the_design_exchange/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# URIs for user-specific views and pages
# These are included in the main url patterns with a "/users/" prefix
# Main URIs
urlpatterns = patterns('the_design_exchange.views',
    url(r'^', include('design_methods.urls')),
)

design_methods/models.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.db import models
from django.db.models.signals import post_save

"""
An extended user profile for TDE, with custom fields and methods
"""

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    role = models.TextField(null=True)


"""
Create a profile upon user creation
"""

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

"""
A Model representing a directional relationship between two users.
Used for user-to-user interactions such as messaging

Will be referred to as UUR for brevity
"""
class UserToUserRelationship(models.Model):
    subject_user = models.ForeignKey('auth.User', related_name="subject_users")
    object_user  = models.ForeignKey('auth.User', related_name="object_users")

    class Meta:
        unique_together = ('subject_user', 'object_user')

"""
A Model for a user-to-user message, which uses the UUR as a foreign key

The next and previous message fields create a doubly-linked list of messages and their replies
"""
class Message(models.Model):
    users = models.ForeignKey('UserToUserRelationship')
    title = models.TextField()
    content = models.TextField()
    sent_at = models.DateTimeField('Sent at')
    previous_message = models.ForeignKey('Message', null=True, related_name="previous_messages")
    next_message = models.ForeignKey('Message', null=True, related_name="next_messages")

"""
A Model for a design method. The contents of a method is broken down as follows:

Purpose: what is the method used for? what design problems does it solve?
Procedure: how do you apply the method?
Principles: what kinds of design principles is this method based on? why does it work?
"""

class Method(models.Model):
    title = models.TextField()
    purpose = models.TextField()
    procedure = models.TextField()
    principles = models.TextField()

    # TODO figure out constraints

    # find author
    def author(self):
        return UserToMethodRelationship.objects.get(
            method = self,
            is_author = True).user

"""
A Model for a relationship between a method and a user (non-directional)

This gives a flexible way to map various ways that users can be related to a method, such as
rating, favoriting, creating, commenting, and other future functions. It also keeps the database
in BCNF and makes it extendable to additional features.

For the sake of efficiency, one-to-one relationships with no extra information are stored here

Will be referred to as UMR for brevity
"""

class UserToMethodRelationship(models.Model):
    user = models.ForeignKey('auth.User')
    method = models.ForeignKey('Method')

    # one-to-one fields with no extra content
    is_author = models.BooleanField()
    is_favorite = models.BooleanField()

    class Meta:
        unique_together = ('user', 'method')

"""
A Model for a rating on a method, using the UMR as a foreign key
"""

class MethodRating(models.Model):
    umr = models.ForeignKey('UserToMethodRelationship')
    rating = models.IntegerField()

"""
A Model for a comment, using the UMR as a foreign key

Users can comment on both methods and method comments
"""

class Comment(models.Model):
    umr = models.ForeignKey('UserToMethodRelationship')
    content = models.TextField()
    reply_to = models.ForeignKey('Comment', null=True, related_name="replies")

the_design_exchange/views.py
# Do we need views in here?

the_design_exchange/templates/methods/details.html
{% extends "base.html" %}

{% block subtitle %}
{{ method.title }}
{% endblock %}

{% block content %}
<section id="upper_box_general">
  <div class="inner_title"><b>Design Method: <b><em>{{ method.title }}</em></div>
    <div class="search_box">
      <form>
        <input type="text" placeholder="Jump to another method..." class="inputbox" id="searchinput">
        <button type="button" id="search_button" class="btn">Search</button>
      </form>
    </div>
</section>
<article class="method_element" id="author">
  <div class="method_element_tittle_wrapper"><em class="method_element_tittle">Author</em></div>
  {% url user_details method.author.id as user_link %}
  <p><a href="{{ user_link }}">{{ method.author }}</a></p>
</article>
<article class="method_element" id="purpose">
  <div class="method_element_tittle_wrapper"><em class="method_element_tittle">Purpose</em></div>
  <p>{{ method.purpose }}</p>
</article>
<article class="method_element" id="procedure">
  <div class="method_element_tittle_wrapper"><em class="method_element_tittle">Procedure</em></div>
  <p>{{ method.procedure }}</p>
</article>
<article class="method_element" id="principles">
  <div class="method_element_tittle_wrapper"><em class="method_element_tittle">Principles</em></div>
  <p>{{ method.principles }}</p>
</article>
<article class="method_element" id="citations">
  <div class="method_element_tittle_wrapper"><em class="method_element_tittle">Citations</em></div>
</article>
{% endblock %}

the_design_exchange/templates/methods/index.html
{% extends "base.html" %}

{% block subtitle %}
Methods
{% endblock %}

{% block content %}
{% if method_list %}
    <ul>
      {% for method in method_list %}
        {% url method_details method.id as method_link %}
        <li><a href="{{ method_link }}">{{ method.title }}</a></li>
      {% endfor %}
    </ul>
{% else %}
    <p>No methods have been created.</p>
{% endif %}
{% endblock %}

the_design_exchange/templates/methods/new.html
{% extends "base.html" %}

{% block subtitle %}
Create Method
{% endblock %}

{% block content %}
<h1>Create Method</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p><input type="submit" value="Send"></p>
</form>
{% endblock %}